module.exports = userSeed = {
    [{
            first: "Mohammed",
            last: "Avdol",
            username: "MagiciansRed",
            email: "mavdol@gmail.com",
            password: "password",
            location: "Egypt",
            phoneNumber: "1234567",
            flakeScore: "0.01",
            bio: "test",
            activitiesCreated: [],
            activitiesJoined: [],
            lastLogin: "",
            status: "test"
        },
        {
            first: "Polnareff",
            last: "Jean",
            username: "SilverChariot",
            email: "pjean@gmail.com",
            password: "password",
            location: "France",
            phoneNumber: "1234567",
            flakeScore: "0.2",
            bio: "test",
            activitiesCreated: [],
            activitiesJoined: [],
            lastLogin: "",
            status: "test"
        },
        {
            first: "Kakyoin",
            last: "Noriaki",
            username: "HeirophantGreen",
            email: "knoriaki@gmail.com",
            password: "password",
            location: "Japan",
            phoneNumber: "1234567",
            flakeScore: "0.03",
            bio: "test",
            activitiesCreated: [],
            activitiesJoined: [],
            lastLogin: "",
            status: "test"
        },
        {
            first: "Joseph",
            last: "Joestar",
            username: "PurpleHermit",
            email: "jjoestar@gmail.com",
            password: "password",
            location: "England",
            phoneNumber: "1234567",
            flakeScore: "0.04",
            bio: "test",
            activitiesCreated: [],
            activitiesJoined: [],
            lastLogin: "",
            status: "test"
        }, {
            first: "Jotaro",
            last: "Joestar",
            username: "StarPlatinum",
            email: "jutes@gmail.com",
            password: "password",
            location: "Japan",
            phoneNumber: "1234567",
            flakeScore: "0.05",
            bio: "test",
            activitiesCreated: [],
            activitiesJoined: [],
            lastLogin: "",
            status: "test"
        }, {
            first: "Iggy",
            last: "Pop",
            username: "ZaFool",
            email: "iggy@gmail.com",
            password: "password",
            location: "New York",
            phoneNumber: "1234567",
            flakeScore: "0.06",
            bio: "test",
            activitiesCreated: [],
            activitiesJoined: [],
            lastLogin: "",
            status: "test"
}]
}

